module.exports = {
    TestingEnvironment: 'QA',
    wait: 80000,
    longWait: 500000,
   // account_name: 'qa11.triveni.gherde@gisqa.mercer.com',
    user_name: 'qa11.triveni.gherde@gisqa.mercer.com',
    pass_word: 'Amit@123',
    urlhri: 'https://consultant-qaf.mercermarketplace365plus.com',
    amit_test_url: 'https://consultant-qaf.mercermarketplace365plus.com/#/wizard/14748/2018/demographicUpload',
    test_url: 'https://consultant-qaf.mercermarketplace365plus.com/#/wizard/14809/2018/demographicUpload',
    ss : 'amit' ,
    client_code : 'test1',
    ssn_no : '777700001',
    audit_url: 'https://docman-qaf.mercer.com/docmanadmin/index.aspx',
    date1: '12/25/2017',
    urlhriHR: 'https://hr-qaf.mercermarketplace365plus.com/Account/Login',
    user_nameHR: 'Stark2@house.com',
    pass_wordHR: 'stark@123',
    correction_date_e1: '3/30/2018',
    first_name: 'Amit',
    first_name1: 'Arun',
    gender: 'M',
    gender1: 'M',
    pincode: '42620',
};